### ISSUE TITLE
`ocrd-cor-asv-ann-evaluate --help` fails

### ISSUE THREAD

**Issue by stweil** [ASVLeipzig/cor-asv-ann#3]
It raises a `KeyError` exception.

**Comment by bertsky** [comment]
Are you sure you already have the current version? I remember fixing things in the processor's constructor 5 days ago...

**Comment by stweil** [comment]
Then we need https://github.com/OCR-D/ocrd_all/pull/63.

**Comment by stweil** [comment]
Ah, sorry, I just repeated the test with an actual OCR-D/ocrd_all and the problem is indeed fixed.
